@startuml 
title Add Task Diagram
skinparam titleFontSize 60
|Router|
start
repeat: Received request
if (request.url === "/tasks"?) then (false)
    :Response status code:
    **404 (NOT_FOUND)**;
    stop

else (true)
    if (request.method === "POST"?) then (false)
        :Response status code:
        **405 (METHOD_NOT_ALLOWED)**;
        stop

    else (true)
        |Task Controller|
        :Received request from Router;
        :Execute **addTask()** function;
        :Extract user_id from request body;
        :Extract token from request header Authorization;
        |User Controller|
        :Execute **checkTokenValid(user_id,token)** function;
        |Database|
        :Query check user match with token & user_id;
        |User Controller|
        :Receive result from query;
        |Task Controller|
        if (Result is true?) then (false)
            :Response status code:
            **400 (BAD_REQUEST)**;
            'Validation failed
            stop
        else (true)
            :Extract data from request body;
            if (Input data validation success?) then (false)
                :Response status code:
                **400 (BAD_REQUEST)**;
                'Validation failed
                stop
            else (true)
                |Database|
                :Add task data into Database;
                |Task Controller|
                :Response status code:
                **201 (CREATED)**;
            endif
        endif
    endif
endif
|Router|
backward:Continue listen request;
repeat while (Listen to request)    
@enduml