@startuml 
title Add Task Diagram
skinparam titleFontSize 60
|Router|
start
repeat: Received request
if (request.url === "/tasks"?) then (false)
    :Response status code:
    **404 (NOT_FOUND)**;
    stop

else (true)
    if (request.method === "POST"?) then (false)
        :Response status code:
        **405 (METHOD_NOT_ALLOWED)**;
        stop

    else (true)
        |Controller|
        :Received request from Router;
        :Execute **addTask()** function;

        if (Input validation success?) then (false)
            :Response status code:
            **400 (BAD_REQUEST)**;
            'Validation failed
            stop
        else (true)
            |Database|
            :Insert task data into Database;
            |Controller|
            :Response status code:
            **201 (CREATED)**;
        endif
    endif
endif
|Router|
backward:Continue listen request;
repeat while (Listen to request)    
@enduml