@startuml
title Delete Task Diagram
skinparam titleFontSize 60
|Router|
start
repeat: Received request

if (request.url === "/tasks/id"?) then (false)
    :Response status code:
    **404 (NOT_FOUND)**;
    stop
else (true)
    if (request.method === "DELETE"?) then (false)
        :Response status code:
        **405 (METHOD_NOT_ALLOWED)**;
        stop
    else (true)
        |Controller|
        :Received request from Router;
        :Execute **deleteTask()** function;

        if (Input validation success?) then (false)
            :Response status code:
            **400 (BAD_REQUEST)**;
            'Validation failed
            stop
        else (true)
            |Database|
            if (Task exists in Database?) then (false)
                |Controller|
                :Response status code:
                **404 (NOT_FOUND)**;
                note left: Task not found
                stop
            else (true)
                |Database|
                :Delete task from Database;
                |Controller|
                :Response status code:
                **200 (OK)**;
            endif
        endif
    endif
endif

|Router|
backward: Continue listening for requests;
repeat while (Listen to request)
@enduml