@startuml 
title Login Diagram
skinparam titleFontSize 60
|Router|
start
repeat: Received request
if (request.url === "/users/login"?) then (false)
    :Response status code:
    **404 (NOT_FOUND)**;
    stop

else (true)
    if (request.method === "POST"?) then (false)
        :Response status code:
        **405 (METHOD_NOT_ALLOWED)**;
        stop

    else (true)
        |Controller|
        :Received request from Router;
        :Execute **login()** function;

        if (Input validation success?) then (false)
            :Response status code:
            **400 (BAD_REQUEST)**;
            'Validation failed
            stop

        else (true)
            |Database|
            :Query user data from Database;


            if (User found?) then (false)
                |Controller|
                :Response status code:
                **404 (NOT_FOUND)**;
                note left: User not found
                stop
            
            else (true)
                |Controller|
                if (Password matches?) then (false)
                    |Controller|
                    :Response status code:
                    **401 (UNAUTHORIZED)**; 
                    stop
                
                else (true)
                    :Response status code:
                    **200 (OK)**;
                endif
            endif
        endif
    endif
endif

|Router|
backward:Continue listen request;
repeat while (Listen to request)    
@enduml