@startuml 
title Get Task Diagram
| Router |
start
repeat: Recieve request 
    if (Check request.url === "/task") then (false)
    :Response status code: error 404(not found);
    else (true)
        if (Check request.method === "GET") then (false)
        :Response status code: error 405 (method not allowed);
        else (true)
            | Controller |
            :Receive request from router;
            :token is taken from request.headers['data'];
            if (Is token valid) then (false)
            :return status code error and require validated data;
            | Router |
            else (true)
                | Task Model |
                :Recieve request form controller;
                | Database |
                :Execute query and return value;
                | Task Model |
                :Revieved Value;
                :Transfering data to Controller;
                | Controller |
                :Recieved data;
                :Transfering data to Router;
                | Router |
                :Recieved data;
            endif
        endif
    endif
stop
@enduml