@startuml
|Router|
start
repeat: Receive request
if (Check request.url === "/task/:id") then (false)
    :Response status code: error 404 (not found);
else (true)
    if (Check request.method === "DELETE") then (false)
        :Response status code: error 404 (not found);
    else (true)
        |Controller|
        :Receive request from router;
        :token is taken from request.headers['data'];
        if (Is token valid?) then (false)
            :return status code error and require token;
            |Router|
        else (true)
            |Controller|
            :get task id from request;
            if (task id is valid) then (false)
                :return status code error and require valid task id;
                |Router|
            else (true)
                |Task Model|
                :receive task id to delete from controller;
                |Database|
                :delete task from database;
                :return message complete to task model;
                |Task Model|
                :receive message from database;
                :transfer message to controller;
                |Controller|
                :receive message from task model;
                :transfer message to router;
                |Router|
                :receive message from controller;
            endif
        endif
    endif
endif
backward: continue listen request;
repeat while (listen to request)
@enduml