@startuml
left to right direction
actor "User" as user
rectangle TodoApp {
  usecase "Logout" as logout
  usecase "Filter Task" as filter
  usecase "Complete Task" as completeTask
  usecase "Delete Task" as deleteTask
  usecase "Edit Task" as editTask
  usecase "View Task List" as viewTask
  usecase "Creat Task" as createTask
  usecase "Login" as login
  usecase "Register" as register
}
user --> logout
user --> filter
user --> completeTask
user --> deleteTask
user --> editTask
user --> viewTask
user --> createTask
user --> login
user --> register
@enduml

